### ISSUE TITLE
Notes on Assignment for February 15th

### ISSUE THREAD

**Issue by natenolting** [aatishballa/BUAD-3283-ecom-web-dev#3]
Looks good! A couple things that could be improved:

* [x] #3 Modularize elements on template. How could you break out elements on your page even more so that each element is doing one thing? For instance, instead of your [sidebar](https://github.com/aatishballa/BUAD-3283-ecom-web-dev/blob/4f55e4b2e4a039cdb55713b73076f3653d1b8e4f/assignments/February_15/index.php#L8) being hardcoded in `index.php` could that be broken out into its own file where the navigation is handled?
* [x] #4 Create a dynamic navigation for template. Again like above, but try and make your navigation elements dynamic somehow. Maybe you use the `scandir` function like I used in the class example, maybe you use an array of elements. There are many different ways of dealing with this.
* [x] #5 Create a mechanism where page content can be passed in dynamically via URL. Perhaps capturing a $_GET variable and using that to switch between your article1.php and article2.php

You can close this issue out when you are complete.

**Comment by aatishballa** [comment]
#3 divided into nav, content and footer sections
#4 navi.php does the navigation
#5 contact us section passes post variables from a form to another page.

@natenolting  Hi, Professor Nate. I have made a few changes. Could you please take a alook at it to see if I got it correct? Thanks!
